- src/components/Footer.jsx
- src/components/Navbar.jsx
- src/components/home/Banner.jsx
- src/components/home/Contact.jsx
- src/components/home/Universities.jsx
- In Navbar fixed signup button coming in next row, missing phone number field
- In Banner fixed margin problem where content was congested in some smaller screen
- In Universities, Header line 'Participating universities in CUET' and bottom line 'view more colleges' were missing
- In Contact, fixed inputs fields having no gap in some smaller screens, need help popup position and fixed typo in textarea field 'Raeson' to 'Reason'
- In footer, fixed font, added gap between icon and text
> Fixes in Navbar, Banner, Universities, Contact and Footer

- src/pages/Aboutpage.jsx
- fixed Navbar and Body not aligning
- fixed overlapping waves
- added footer
> fixes from review

- src/components/Footer.jsx
- src/components/Navbar.jsx
- src/components/home/Banner.jsx
- src/components/home/Contact.jsx
- src/components/home/HomeSteps.jsx
- src/components/home/StepGuide.jsx
- src/components/home/SubjectTopic.jsx
- src/components/home/Testinomials.jsx
- src/components/home/Universities.jsx
added fixes
- Fixed navbar dropdown
- Fixed 'Live Notification' popup position
- Fixed 'Challenge Yourself' Position on mobile screens
- Fixed Layout and Margin on Steps
- Fixed Footer layout
> Homepage responsive

- src/pages/Aboutpage.jsx
> latest fixes in About page, including waves vector at bottom

- src/components/Courses/TopicContainer.jsx
- src/components/home/FAQ.jsx
- src/components/home/faq.css
- src/pages/Homepage.jsx
> Completed-faq

- src/components/Syllabus/SyllabusCard.jsx
- src/pages/Syllabus.jsx
> Added links in syllabus page

- src/App.js
- src/components/Courses/Course.jsx
- src/components/home/SubjectTopic.jsx
- src/utils/constants.js
fixed routes issues and minor changes
> Fixed minor issues

- src/App.js
- src/components/Courses/Course.jsx
- src/components/Courses/SubtopicPage.jsx
- src/components/Courses/TopicContainer.jsx
- src/components/home/DomainTopic.jsx
> Feat minor fixes 03

- src/App.js
- src/components/Packs/PacksPage.jsx
- src/components/Packs/PriceCard.jsx
> Minor UI fixes

- src/components/Login/ForgotPassword.jsx
- src/components/Login/ResetPassword.jsx
- src/components/Packs/PacksPage.jsx
> Minor-api-fix

- src/components/Login/ForgotPassword.jsx
- src/components/Login/ResetPassword.jsx
> Forgot-password-api-resolve

- src/components/Login/ForgotPassword.jsx
- src/components/Login/ResetPassword.jsx
Added toastify in forgot password
> Added toastify in forgot password

- src/pages/UniversityPage.jsx
> UI fix of university page

- src/components/Courses/DomainContainer.jsx
- src/components/Navbar.jsx
- src/components/home/Banner.jsx
- src/components/prepmodules/Navbar.jsx
> minor UI changes

- src/components/FixedNavbar.jsx
- src/components/Navbar.jsx
- src/components/Packs/PackFaq.jsx
- src/components/Packs/PacksPage.jsx
- src/components/Packs/PriceCard.jsx
- src/components/Packs/css/PackFaq.css
- src/components/Test/TestPage.jsx
- src/components/home/Banner.jsx
- src/components/home/FAQ.jsx
- src/components/home/Testinomials.jsx
- src/index.css
- src/utils/constants.js
Pricing page content and UI fixes
Basic UI fixes
> UI fixes 05

- src/components/Packs/PackFaq.jsx
- src/components/Packs/PacksPage.jsx
- src/components/Packs/PriceCard.jsx
- src/components/Packs/css/PackFaq.css
Pricing page UI fix mobile app
> Pricing page UI fix for mobile app

- src/components/Footer.jsx
changed color of term and condition and privacy
added hover effect to all clickable element 
added anchor element so that after clicking person can directly mail,call, and directly open adress on map
changed width of line 
changed background color of footer
> minor changes

- src/components/mathJax/MathText.jsx
- src/components/mathJax/mathText.css
- src/components/practicetest/PracticeTestMain.jsx
- src/components/practicetest/PracticeTestQues.jsx
- src/components/prepmodules/PrepModulesMultipleSubquestion.jsx
- src/components/prepmodules/PrepModulesSingleSubquestion.jsx
- src/index.css
> color improved and height fixed

- src/components/Login/LoginForm.jsx
- src/components/Packs/PackFaq.jsx
- src/components/Packs/PacksPage.jsx
- src/components/Packs/PriceCard.jsx
- src/components/Packs/css/PackFaq.css
- src/components/Test/TestPage.jsx
- src/components/Test/Testcard.jsx
- src/components/home/FAQ.jsx
Content fix and basic UI update
> Content fix and basic UI update

- src/components/Login/LoginForm.jsx
- src/components/Navbar.jsx
- src/components/Packs/PacksPage.jsx
- src/components/Signup/SignupForm.jsx
- src/components/burgerAndMenu/BurgerAndMenu.jsx
Removed razorpay data and password from local storage
Fixed hamburger
> Removed razorpay data and password from local storage

- src/components/Courses/SubtopicPage.jsx
- src/components/Packs/PackFaq.jsx
- src/components/Packs/PacksPage.jsx
- src/components/Packs/PriceCard.jsx
- src/components/Test/TestPage.jsx
- src/components/dashboardNew/pages/account-settings/TabAccount.jsx
- src/utils/constants.js
- src/utils/courses.js
> Basic fixes

- src/components/Packs/PacksPage.jsx
Selected subjects improved in pricing page
> Selected subjects improved

- src/components/Login/LoginForm.jsx
- src/components/Signup/SignupForm.jsx
- src/pages/Login.jsx
- src/pages/Signup.jsx
> Login-signup-fix

- src/components/practicetest/PracticeTestMain.jsx
- src/components/prepmodules/PrepModules.jsx
> URL-change-required

- src/components/Test/Testcard.jsx
- src/components/practicetest/PracticeTestMain.jsx
- src/components/prepmodules/PrepModules.jsx
- src/utils/constants.js
> URL change

- src/components/Packs/PacksPage.jsx
- src/components/Test/Testcard.jsx
- src/components/dashboardNew/pages/account-settings/TabSecurity.jsx
removed access for free user in domain subjects
passed GE and GT as default for jumbo and mega pack
ui fix
> removed access for free user in domain subjects

- src/components/home/Banner.jsx
Fixed live notification position
> Fixed live notification position

- src/App.js
- src/components/Packs/PacksPage.jsx
- src/components/home/Banner.jsx
> Fixed content

- src/components/BlogCard/Data.js
- src/components/BlogCard/Grid.jsx
- src/components/Navbar.jsx
- src/components/Packs/PriceCard.jsx
- src/components/Test/TestPage.jsx
- src/components/Test/Testcard.jsx
card link were fixed
minor changes
> All minor changes fixed and card links were corrected to right path

- package-lock.json
- package.json
- src/App.js
- src/components/BlogCard/Blog.css
- src/components/BlogCard/Data.js
- src/components/BlogCard/Grid.jsx
- src/components/BlogCard/Post.jsx
- src/components/Login/LoginForm.jsx
- src/components/Navbar.jsx
- src/components/dashboardNew/pages/account-settings/TabAccount.jsx
- src/components/dashboardNew/pages/account-settings/TabSecurity.jsx
> blog updated

- src/components/BlogCard/Data.js
> blog fixed

- src/components/Courses/TopicContainer.jsx
- src/components/Signup/SignupForm.jsx
- src/components/Test/Testcard.jsx
Google signup fix
Economics fixed
> google signup fix
